### ISSUE TITLE
support power on and power off from tools to spalloc via here

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/RemoteSpiNNaker#10]
this will support power measurements better, by actually turning off machine between detection and loading.

**Comment by dkfellows** [comment]
Current recommendation is to not power off the machine because of other issues like SpiNNakerManchester/spalloc_server#37.

**Comment by dkfellows** [comment]
We do not plan to do this because power-cycling a (sub-)machine may bring up boards in a different configuration. Yes, spalloc can do it (both old and new) but it is not recommended that anyone actually use this feature unless they're fully aware of the consequences.

Instead, @rowleya has been working a lot on making partitioning, placement, routing and data generation *much* faster, some of which involves running things on the machine. We believe that to be a far better solution for the wider issues,
