### ISSUE TITLE
Support some sort of timeout on jobs

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/RemoteSpiNNaker#38]
Jobs can get stuck for various reasons (they are just user scripts).  There should be some way of deciding that a job has got stuck.  I have no idea how this would be decided!  It could be a timeout, but we would need to be careful in that case since users could run jobs for a long time in general.

**Comment by andrewgait** [comment]
Is there some way of just having a general time limit on jobs using RemoteSpiNNaker, and that if users need to run longer jobs then they need to contact us in order to work out a way of doing it?  (Perhaps there is a way of using multi-run via RemoteSpiNNaker that will allow them to run longer jobs anyway...?)

**Comment by alan-stokes** [comment]
its worth noting that there was a issue (somewhere, and i have yet to find it) discussing how reset and the tracking of time ran for stuff like the HBP portal are completely off. 

the issue is that noone knows how long a job will take, and to be honest, theres no flags that can give said justification. mapping? well reset and add new pop and that could be spinning around a lot...... 

maybe a block of code could be augmented to say the stay live idea, where the portal could ask the software to check its state and see if anythings running?

**Comment by rowleya** [comment]
We could have a fixed time with an option for users to make that longer using the "hardware configuration".  This would have to *not* allow the user to make it infinite, and potentially have a (fairly long - maybe 1 week?) absolute maximum.

**Comment by alan-stokes** [comment]
the 1 week limit might be doable, until we're supporting scripts that take that long to just map. but maybe. But this goes kinda away from "how do we detect when a script has failed" and gone "anything over a week has by default crashed". Im not against it. but it would need to be some code with neon lights so future us can find it easily. lol

**Comment by dkfellows** [comment]
> Is there some way of just having a general time limit on jobs using RemoteSpiNNaker

We can most certainly implement a timeout in how long we wait for the worker subprocess. The real question is whether we want to allow changing the wait time via any API; a fixed wait time (7&times;24 hours, say) is easy to implement, but changing wait times is quite a lot more complicated (especially if the wait time can be changed after submission or allow manual killing, as those force a different way of storing the state).
